### PR TITLE
CI: Print verbose `ctest` output to help determine slow tests

### PR DESCRIPTION
**Pull request by yyny**
`--verbose` will print the `stdout`/`stderr` output of running tests.

### CODE REVIEW

**Comment by trflynn89** [comment]
How does this identify slow tests? The only tests that take an appreciable amount of time are JS, Wasm, and Web tests, and this only prints the overall execution times of each of those tests (which is already logged without this flag).

--verbose is certainly useful for some specific testing, but IMO adds too much noise to have enabled by default. It's already tedious to find the real failure reasons without having to sift through more stdout.

**Comment by yyny** [comment]
You can click "Show timestamps" in Github Actions to see exactly when each line was printed. From there you could use an eyeball test or paste the output into a script.

I am suspicious that certain tests are occasionally getting stuck or take much longer than usual, also because of https://github.com/LadybirdBrowser/ladybird/pull/2629.

Screenshot from 2024-11-29 21-31-34

**Comment by trflynn89** [comment]
Yeah something is getting stuck on macOS - my plan to identify those was to expand headless-browser's --verbose flag to log both the start and end of each test (it currently just logs the start) and enable that flag.

To identify slow Web tests, headless-browser's --verbose flag will also already print the slowest N tests, but the above change would also be trivial to print the time for *every* Web test.

I think that'd be more fruitful than making all of ctest verbose + relying on reported clock times

**Comment by yyny** [comment]
Yes, `ctest --verbose` is intended as a quick short-term solution, of course.

> my plan to identify those was to expand headless-browser's --verbose flag to log both the start and end of each test

LibWeb tests in CI currently print neither their start nor end time, so that would be very useful indeed.
You _might_ also be able to `fflush(stdout);` in Github Actions and still have it record it in case of a crash. I know this is possible on Gitea and builds.sr.ht, but I don't have as much experience on Actions. If that works then you could print the currently executing test and append the execution time when it completes, without increasing the line count.

Also, AFAIK the slowest N tests _only_ get printed after all tests have ran, which is not very useful when `ctest` ends the process early.

**Comment by trflynn89** [comment]
I pushed the current impl of this I've been using in my fork here:
https://github.com/trflynn89/ladybird/tree/headless-log

**Comment by yyny** [comment]
Well alright, I will close this then, would be nice if that could get merged soon, because many CI runs are timing out right now, and it would be great if we could find some ways to alleviate that.

Also, it might still make sense to increase the timeout a _little_, to something like `1800s (30min)` up from `1500s (25min)`. From some of the passing CI runs, even `1480.64s` & `1439.02s` get dangerously close to timing out.

**Pull request closed without merging**
