### PR TITLE
LibWeb: Implement the nonce attribute

### PR DESCRIPTION
**Pull request by gmta**
At least, as far as we can implement it without having a CSP list in our policy container. :^)

* `HTMLOrSVGElement` is a factored out mixin that is now used by `HTMLElement`, `SVGElement` and `MathMLElement`
* Fixes at least 2 WPT tests completely, plus some additional subtests

### CODE REVIEW

**Review by tcl3 — COMMENTED** [review]
I found a minor issue where the nonce attribute doesn't work as expected when queried on an custom SVG element.

Test case reduced from: http://wpt.live/content-security-policy/nonce-hiding/nonces.html:

```html
<!DOCTYPE html>
<script>
    // This works as expected
    let htmlElement = document.createElementNS("http://www.w3.org/1999/xhtml", "blah");
    console.log(`htmlElement.nonce: '${htmlElement.nonce}'`);

    // This does not (should be empty string, but is undefined)
    let svgElement = document.createElementNS("http://www.w3.org/2000/svg", "blah");
    console.log(`svgElement.nonce: '${svgElement.nonce}'`);
</script>
```
I think this is because this code path is hit in `ElementFactory.cpp`
https://github.com/LadybirdBrowser/ladybird/blob/a0ee86db0453de5a2330955235667fcc43cd11b4/Userland/Libraries/LibWeb/DOM/ElementFactory.cpp#L678-L682

This path creates a `DOM::Element`, which doesn't inherit  `HTML::HTMLOrSVGElement<T>`, which may be what's causing the problem.

**Comment by gmta** [comment]
Good find! That's defined in [the SVG2 spec](https://svgwg.org/svg2-draft/types.html#ElementsInTheSVGDOM):

> Elements in the SVG namespace whose local name does not match an element defined in any specification supported by the software must nonetheless implement the [SVGElement](https://svgwg.org/svg2-draft/types.html#InterfaceSVGElement) interface.

**Comment by gmta** [comment]
MathML core defines it as well, albeit a bit more convoluted:

https://w3c.github.io/mathml-core/#html-and-svg
> All the nodes representing [MathML elements](https://w3c.github.io/mathml-core/#dfn-mathml-element) in the DOM must implement, and expose to scripts, the following MathMLElement interface.

https://w3c.github.io/mathml-core/#mathml-elements-and-attributes
> The term MathML element refers to any element in the [MathML namespace](https://infra.spec.whatwg.org/#mathml-namespace).

**Comment by gmta** [comment]
@tcl3 picked it up in #2075 since it's a separate issue from the `nonce` implementation

**Pull request merged**
