### PR TITLE
Everywhere: Convert from_string_view -> from_string_literal where static

### PR DESCRIPTION
**Pull request by asutoshvariar**
In AK/Error.h, the comments mention using from_string_literal over from_string_view where the error message is static/typed out.

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
`Everywhere:` is fine for things like this. Or you can break it into smaller commits.

This has merge conflicts so you'll need to rebase it on master and fix those.

**Comment by asutoshvariar** [comment]
> `Everywhere:` is fine for things like this. Or you can break it into smaller commits.
> 
> This has merge conflicts so you'll need to rebase it on master and fix those.

Will do, thanks for the guidance!

**Comment by ADKaster** [comment]
@asutoshvariar It looks like your force pushes have ended up dropping your actual changes. You should be able to recover the diff using `git reflog`

**Comment by asutoshvariar** [comment]
> @asutoshvariar It looks like your force pushes have ended up dropping your actual changes. You should be able to recover the diff using `git reflog`

Will do, sorry about that!

**Comment by asutoshvariar** [comment]
> Looks good, but this has ended up with a conflict again. (`Userland/Libraries/LibGfx/Font/OpenType/Cmap.cpp` was deleted.) I tried fixing it myself but either you didn't grant access (fair enough!) or I really can't remember how to do that properly.

Thanks for the guidance! I was a bit stuck on what to do, because I couldn't use the online editor to view it. Does everything look good now?

**Comment by AtkinsSJ** [comment]
I think so. I'll run CI to make sure, and try and catch it right away before it gets a conflict again. 😅

**Comment by asutoshvariar** [comment]
Got it, fingers crossed :grin:

**Comment by AtkinsSJ** [comment]
:tada: Thanks for your patience with this!

**Pull request merged**
