### PR TITLE
LibWeb: Implement `transition` property 🎉 

### PR DESCRIPTION
**Pull request by AtkinsSJ**
We're still failing a lot of WPT tests, I think due to lack of events and some other OM things, but the basic functionality works pretty solidly.

There's a small hack in the included test. Without it, the reported `left` value after the transition from `0px` to `200px` completes, is `0px` even though the div is visibly at `200px`. I suspect this is a pre-existing bug but honestly I'm not sure. Our attempt at implementing the contradictory animation specs still confuses me. 😅 

### WPT Results Before
Ran 118 tests finished in 64.0 seconds.
  • 14 ran as expected. 0 tests skipped.
  • 2 tests crashed unexpectedly
  • 2 tests had errors unexpectedly
  • 16 tests timed out unexpectedly
  • 97 tests had unexpected subtest results

### WPT Results After
Ran 118 tests finished in 74.1 seconds.
  • 18 ran as expected. 0 tests skipped.
  • 4 tests crashed unexpectedly
  • 3 tests had errors unexpectedly
  • 16 tests timed out unexpectedly
  • 90 tests had unexpected subtest results

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
CI spotted that I missed a visit(). I'll try and fix that up tomorrow.

**Comment by AtkinsSJ** [comment]
Fixed the missing `visit()`.

**Comment by mattco98** [comment]
Amazing!! Thanks for all your hard work here, I'm very happy to see transitions finally ready to go 😄

**Comment by AtkinsSJ** [comment]
> Amazing!! Thanks for all your hard work here, I'm very happy to see transitions finally ready to go 😄

Thank *you* for doing so much if the work originally! This stuff is hard. 😅

**Pull request merged**
