### PR TITLE
LibXML: Allow empty systemid when parsing document type

### PR DESCRIPTION
**Pull request by f-cramer**
This fixes at least one WPT und /domparsing

### CODE REVIEW

**Comment by alimpfard** [comment]
Looks good, have you checked if this is the only place we were mistakenly doing `foo+` instead of `foo*`?

**Comment by alimpfard** [comment]
Thanks for looking into it!

**Comment by f-cramer** [comment]
Can I do anything more to get this merged?

**Comment by alimpfard** [comment]
Oh sorry, I forgot to push the button 😅

**Pull request merged**
