### PR TITLE
 Userland: Remove some SerenityOS checks

### PR DESCRIPTION
**Pull request by circl-lastname**
This removes basically all checks for the AK_OS_SERENITY macro with the exception of LibCore. Business logic of the code remains unchanged (except for LibAudio which removes AudioServer support), and 99% of changes should still be syncable with SerenityOS.

### CODE REVIEW

**Comment by ADKaster** [comment]
Many of these SerenityOS check removals were premature.

The changes to LibFilesystem, LibMain, LibTLS, LibThreading, LibTimeZone, and LibJS should have had a larger discussion prior to merge.

**Comment by awesomekling** [comment]
> Many of these SerenityOS check removals were premature.
> 
> The changes to LibFilesystem, LibMain, LibTLS, LibThreading, LibTimeZone, and LibJS should have had a larger discussion prior to merge.

Supporting SerenityOS is not a goal in this project.

**Comment by awesomekling** [comment]
…that said, it’s true that we don’t have to treat it differently from other esoteric systems like Hurd or Haiku :)

so yeah some of this was premature then!

**Comment by circl-lastname** [comment]
> Many of these SerenityOS check removals were premature.
> 
> The changes to LibFilesystem, LibMain, LibTLS, LibThreading, LibTimeZone, and LibJS should have had a larger discussion prior to merge.

Let this comment serve as what you need to add back in if you wanna sync with SerenityOS:
LibFilesystem: The SerenityOS specific ioctl for reading the size of a block device
LibMain: A dbgln
LibTLS: Returning when cacert_file_or_error is an error (why was this Serenity specific?)
LibThreading: Serenity-specific mutex initialization
LibTimeZone: Setting the time zone on SerenityOS
LibJS: Some `dbgln`s, setting the name of a heap allocation, perf signposts, and serenity_mmap usage

Anyway.. uhh, I follow [WP:BOLD](https://en.wikipedia.org/wiki/Wikipedia:Be_bold), feel free to revert if this causes issues going forward

**Pull request merged**
