### PR TITLE
Everywhere: Change static to inline for constexpr variables in headers

### PR DESCRIPTION
**Pull request by dawmd**
Using the `static` keyword to declare a variable in a header may lead to duplication of symbols as they may be created for each translation unit that includes the header. Although the compiler is able to optimize it in some cases, it's not always allowed, e.g. when taking the address of such a variable.

In these changes, we replace the `static` keyword wih `inline` to make sure all translation units refer to the same entities.

Refs LadybirdBrowser/ladybird#945

### CODE REVIEW

**Comment by circl-lastname** [comment]
"Everywhere" is usually used instead of "Treewide"

**Comment by dawmd** [comment]
> "Everywhere" is usually used instead of "Treewide"

Thank you. I'm on a holiday, but when I'm back, I'll edit the PR

**Comment by ADKaster** [comment]
Does this change actually have an impact on the generated code?

**Comment by dawmd** [comment]
> Does this change actually have an impact on the generated code?

Yes, it can. It prevents duplicating static unmutable data in the generated ASM.

**Comment by dawmd** [comment]
Version 2:
* Rebased on top of the current master branch.

**Pull request closed without merging**
