### PR TITLE
CMake: For Debug builds, do no compiler optimizations (-O0)

### PR DESCRIPTION
**Pull request by sideshowbarker**
This change makes Debug builds use the CXX `-O0` option — which tells the compiler to build with no optimizations at all.

Otherwise, Debug builds use the `-Og` option — which, when trying to check frame variables in lldb, can result in an error of this form:

> error: Couldn't look up symbols: __ZN2AK6Detail10StringBaseD2Ev
> Hint: The expression tried to call a function that is not present in the target, perhaps because it was optimized out by
the compiler.

See https://github.com/LadybirdBrowser/ladybird/pull/2190 for an alternative.

### CODE REVIEW

**Comment by shannonbooth** [comment]
Will just link my test results for maintainers for reference for any decision: https://discord.com/channels/1247070541085671459/1247090064480014443/1303515717311660042

While lldb may have some problems in debug mode -

For this change, if merged, I suppose we should maybe document somewhere for a new contributor to aware that this build configuration wont or may not pass test suite due to performance as a disclaimer. Maybe faster PCs might pass it though I suppose.

**Comment by sideshowbarker** [comment]
> Will just link my test results for maintainers for reference for any decision: [discord.com/channels/1247070541085671459/1247090064480014443/1303515717311660042](https://discord.com/channels/1247070541085671459/1247090064480014443/1303515717311660042)

Yeah, given those times and numbers, it seems like we’d be better off doing something like what’s in https://github.com/LadybirdBrowser/ladybird/pull/2190.

> For this change, if merged, I suppose we should maybe document somewhere for a new contributor to aware that this build configuration wont or may not pass test suite due to performance as a disclaimer. Maybe faster PCs might pass it though I suppose.

Yeah, I think even if instead we go with the https://github.com/LadybirdBrowser/ladybird/pull/2190 approach, I’d still need to update the docs with such caveats — probably include a higher-level statement saying something like _“You probably only want to have `-O0` flipped on for a build while you’re examining the state with that build in your debugger. You otherwise probably don’t want to have it on while you’re running WPT tests or in-tree tests and checking the results”._

**Comment by ADKaster** [comment]
Personally I prefer this to #2190 . @trflynn89 any thoughts?

**Comment by trflynn89** [comment]
I'm on the fence. I also probably prefer this over 2190, in the sense that debug builds are for debugging, not performance. And 2190 seems like an opening to having to deal with weird build issues and extra maintenance.

OTOH I feel like learning how to deal with tiny functions being inlined is just a basic part of debugging programs, as well as being comfortable tweaking project build flags to suit the developer's current needs. I would not expect to be able to step into a function like this, for example:
```c++
size_t size() const { return m_size; }
```

So IMO our choices should be: pick this PR, or do nothing. And if only functions like the above are non-inspectable, I'd probably vote do nothing.

**Comment by sideshowbarker** [comment]
Superseded by the docs change in https://github.com/LadybirdBrowser/ladybird/pull/2833

**Pull request closed without merging**
