### PR TITLE
LibCrypto+LibTLS: Little refactoring to remove ASN1 from within SECPxxxr1 methods

### PR DESCRIPTION
**Pull request by devgianlu**

### CODE REVIEW

**Comment by alimpfard** [comment]
🤔 I don't get the motivation, why the shuffling? it seems to just be moving code from one place to another?
Title says "refactoring to remove asn.1", is that something we want to do...?

**Comment by devgianlu** [comment]
> 🤔 I don't get the motivation, why the shuffling? it seems to just be moving code from one place to another? Title says "refactoring to remove asn.1", is that something we want to do...?

The original idea was to make all curves work with integer instead of bytes, that turned out to be a pretty big task which I am not sure how to tackle. However, it seemed reasonable to atleast remove ASN1 encoding/decoding from within `SECPxxxr1` because I wouldn't expect the methods to accept and return ASN1 structures. Moving them to the structs and explicitely declaring the conversion with `to_asn`/`to_uncompressed` felt like a step in the right direction.

**Comment by devgianlu** [comment]
> That reasoning I can accept, please mention it in the commit description as well :)

Updated the commit messages and also the PR title! :)

**Review by alimpfard — APPROVED** [review]
Looks alright.

**Pull request merged**
