### PR TITLE
LibWeb: Defined all the keycodes

### PR DESCRIPTION
**Pull request by Arhcout**
I did this to respond to the issue #974.
I changed the other keys to not have problems with two keys having the same keycode.

### CODE REVIEW

**Comment by matan-h** [comment]
Awesome, I can confirm it does successfully fix #974 :tada:

**Comment by circl-lastname** [comment]
Is the determine_key_code function sitll needed after this change?

**Comment by Arhcout** [comment]
Yes because for example if lowercase 'a' is inputed, it will return the ascii code for uppercase 'A' because that's the documentation

**Comment by circl-lastname** [comment]
Ah

**Comment by AtkinsSJ** [comment]
Looks reasonable, but I'll re-run CI as some of it had expired.

**Comment by AtkinsSJ** [comment]
This doesn't compile at the moment, please update it to fix that.

**Comment by Arhcout** [comment]
I checked the logs and something is weird, the compiler complains about 
`165 | #define __ENUMERATE_KEY_CODE(name, ui_name) \`
It is saying that the macro has two arguments while is use three.
The problem is that this is the old version of the line because I modified it in the commit (you can check):
`#define __ENUMERATE_KEY_CODE(name, ui_name, code) Key_##name = code,`
Maybe I did something wrong while committing my code, I hope you can help (this is my first time contributing to open source sorry)

**Comment by AtkinsSJ** [comment]
As I said on Discord, there's another user of `ENUMERATE_KEY_CODES` that got added after you made your changes:

https://github.com/LadybirdBrowser/ladybird/blob/3d63549edeb161e16087db02b1b2e46231c03a37/Userland/Libraries/LibWeb/UIEvents/KeyCode.h#L163-L172

That's what the error complains about (which is why it says line 165 which doesn't make sense otherwise.)

**Pull request merged**
