### PR TITLE
LibJS: Temporal deprecation and revival part 1

### PR DESCRIPTION
**Pull request by trflynn89**
Our Temporal implementation is woefully out of date. The spec has been so vastly rewritten that it is unfortunately not practical to update our implementation in-place. Even just removing Temporal objects that were removed from the spec, or updating any of the simpler remaining objects, has proven to be a mess in previous attempts.

My strategy here is to basically to remove Temporal entirely from LibJS, and start building it back up, starting with `Temporal.Duration`. I tried a handful of times to catch up to the spec without such a blunt instrument, but there's just too many interdependencies between the Temporal objects for that to work.

Our test262 score will obviously not fare well here, but with this re-implementation, we have the following new passes in `Temporal.Duration`:
```
test/built-ins/Temporal/Duration/compare/argument-string-negative-fractional-units.js                                       ❌ -> ✅
test/built-ins/Temporal/Duration/compare/instances-identical.js                                                             ❌ -> ✅
test/built-ins/Temporal/Duration/from/argument-duration-max.js                                                              ❌ -> ✅
test/built-ins/Temporal/Duration/from/argument-duration-precision-exact-numerical-values.js                                 ❌ -> ✅
test/built-ins/Temporal/Duration/from/argument-non-string.js                                                                ❌ -> ✅
test/built-ins/Temporal/Duration/from/argument-string-fractional-precision.js                                               ❌ -> ✅
test/built-ins/Temporal/Duration/from/argument-string-fractional-units-rounding-mode.js                                     ❌ -> ✅
test/built-ins/Temporal/Duration/from/argument-string-negative-fractional-units.js                                          ❌ -> ✅
test/built-ins/Temporal/Duration/from/argument-string.js                                                                    ❌ -> ✅
test/built-ins/Temporal/Duration/from/subclassing-ignored.js                                                                ❌ -> ✅
test/built-ins/Temporal/Duration/max.js                                                                                     ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/add/argument-duration-max.js                                                     ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/add/argument-not-object.js                                                       ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/add/argument-string-negative-fractional-units.js                                 ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/add/basic.js                                                                     ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/add/precision-exact-mathematical-values.js                                       ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/subtract/argument-duration-max.js                                                ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/subtract/argument-not-object.js                                                  ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/subtract/argument-string-negative-fractional-units.js                            ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/subtract/precision-exact-mathematical-values.js                                  ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/toString/fractionalseconddigits-non-integer.js                                   ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/toString/max-value.js                                                            ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/toString/no-precision-loss.js                                                    ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/toString/order-of-operations.js                                                  ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/toString/round-cross-unit-boundary.js                                            ❌ -> ✅
test/built-ins/Temporal/Duration/prototype/total/no-precision-loss-for-small-units.js                                       ❌ -> ✅
```
(There's also a bunch of `Temporal.Duration` failures, but they are all due to missing other Temporal objects)

### CODE REVIEW

**Review by alimpfard — COMMENTED** [review]
Crypto stuff LGTM.

**Review by shannonbooth — APPROVED** [review]
I think this is definitely the best approach, catching up to the spec was very painful

**Comment by shannonbooth** [comment]
> I think this is definitely the best approach, catching up to the spec was very painful

A lot of the AO's I was previously having trouble catching up to in Duration are updated as part of this PR, should makes things much easier/quicker going forward IMO, even if it means we have to rewrite some stuff

**Comment by trflynn89** [comment]
> A lot of the AO's I was previously having trouble catching up to in Duration are updated as part of this PR, should makes things much easier/quicker going forward IMO, even if it means we have to rewrite some stuff

Yeah it's just too hairy otherwise :sob: e.g. I'm currently working on some of the plain date stuff, which uses `Calendar` - which used to be a JS object but is now just a string. I tried just making that a string in our existing implementation before, and even that was just too intertwined.

**Pull request merged**
