### PR TITLE
LibWeb: Fix "incorrect behavior on select()"

### LINKED ISSUE #1446: LibWeb/HTML: incorrect behavior on select()
when calling select() on an input element it only works for the first time, clicking somewhere else and calling select() again does not work unless you change the text on the element.

incorrect behavior on Ladybird:
ladybird

correct behavior on google chrome:
chrome

HTML code:
```
<script>
    let mySelect = () => {
        let foo = document.getElementById("foo");
        foo.select();
    }
</script>

<input type="text" id="foo"/>
<button style="padding: 15px" id="button" onclick="mySelect()">Select</button>
```

### PR DESCRIPTION
**Pull request by An-n-ya**
This patch resolves the problem outlined in issue #1446. The problem is the cursor_position node could be substituted with any other existing node by the `mousedown` event. Previously, if this new node was not equal to m_text_node, the function would return prematurely without updating the selection.

With this fix, we ensure that the selection is properly updated in such cases, rather than simply exiting the function.

Also, in order to address the issue in #1339, the logic of `document().set_cursor_position` has been put behind to the logic of Selection.

Closes #1446

### CODE REVIEW

**Comment by circl-lastname** [comment]
The Issue number is not needed in the commit name, instead you can put `Closes #1446` inside the pull request description, which will also make GitHub automatically detect the issue this fixes,

**Comment by Gingeh** [comment]
Very good!
Could it be worth adding a test for this?

**Comment by An-n-ya** [comment]
> Very good! Could it be worth adding a test for this?

Normally, we can use `inputNode === document.activeElement` to check if an input is focused, but in Ladybird, `activeElement` is still not right. So, I can only provide a very basic test like this:

```html
<input type="text" id="input" value="foo" />
<input type="text" id="boo"/>
<script src="../include.js"></script>
<script>
    test(() => {
        // simulate issue #1446
        let input = document.getElementById("input");
        let boo = document.getElementById("input");
        input.select();
        boo.select();
        input.select();

        let sel = document.getSelection();
        if (sel.anchorNode) {
            println("PASS");
        }
    });
</script>

```

which doesn't correspond to issue in #1446 precisely, so I think it would be better to complete this test case once we have a more robust interface (e.g., document.activeElement).

**Comment by ronak69** [comment]
The test case in Issue-1446 works fine now but I also checked with `setInterval(mySelect, 3000)` and it does not select.

**Comment by shlyakpavel** [comment]
In light of recent changes, is this still relevant? If so, @An-n-ya, could you please rebase and resolve the conflicts?

**Comment by An-n-ya** [comment]
The function `selection_was_changed` is no longer needed, so this patch is irrelevant to original problem.

**Pull request closed without merging**
