### PR TITLE
LibWeb: Handle empty string in `lang` attribute

### PR DESCRIPTION
**Pull request by pbrw**
If the attribute value is the empty string `(lang="")`, the language is set to unknown. `lang` attribute higher up in the document tree (if exists) is not applied to the content of that element.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang

This fixes 3 WPT tests
https://wpt.fyi/results/html/dom/elements/global-attributes/the-lang-attribute-008.html?label=master&product=ladybird
https://wpt.fyi/results/html/dom/elements/global-attributes/the-lang-attribute-009.html?label=master&product=ladybird
https://wpt.fyi/results/html/dom/elements/global-attributes/the-lang-attribute-010.html?label=master&product=ladybird

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
There's actually a comment in [the spec](https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes) about this:

> If the resulting value is the empty string, then it must be interpreted as meaning that the language of the node is explicitly unknown.

I think that means that an empty string returned from any of the branches should be handled this way, not just from that second one.

**Comment by pbrw** [comment]
@AtkinsSJ Right, thanks. I'm thinking how to implement it to not complicate code too much. Maybe wrap it into lambda for branching and then validate if it's not empty?

**Comment by AtkinsSJ** [comment]
> @AtkinsSJ Right, thanks. I'm thinking how to implement it to not complicate code too much. Maybe wrap it into lambda for branching and then validate if it's not empty?

Sure, or the other option is to save the result instead of returning it immediately, and then check it once at the end.

**Comment by pbrw** [comment]
@AtkinsSJ Created my own tests based on WPT. Created only 2 because the third uses HTTP headers and if I'm not mistaken we can't simulate it atm.

**Review by AtkinsSJ — APPROVED** [review]

**Pull request merged**
