### PR TITLE
LibWeb: Add null checks to several navigation-related methods

### LINKED ISSUE #199: crash on engadget.com
image

Click on article picture, then on the article title, then  article picture, then on the article title

VERIFICATION FAILED: m_ptr at /mnt/avb/work/ladybird/Userland/Libraries/LibJS/Heap/GCPtr.h:174
/usr/local/libexec/../lib/liblagom-ak.so.0(ak_verification_failed+0xbb) [0x7b545f7abe2b]
/usr/local/libexec/../lib/liblagom-web.so.0 Web::DOM::Document::inclusive_ancestor_navigables() 0x10c) [0x7b54606d4adc]
/usr/local/libexec/../lib/liblagom-web.so.0 Web::HTML::NavigableContainer::shared_attribute_processing_steps_for_iframe_and_frame(bool) 0x245) [0x7b54608f50c5]
/usr/local/libexec/../lib/liblagom-web.so.0 Web::HTML::HTMLIFrameElement::process_the_iframe_attributes(bool) 0x1bc) [0x7b546085eafc]
/usr/local/libexec/../lib/liblagom-web.so.0(+0x85f422) [0x7b546085f422]
/usr/local/libexec/../lib/liblagom-web.so.0(+0x8f33c8) [0x7b54608f33c8]
/usr/local/libexec/../lib/liblagom-web.so.0(+0x96dbc9) [0x7b546096dbc9]
/usr/local/libexec/../lib/liblagom-core.so.0 Core::Timer::timer_event(Core::TimerEvent&) 0xb2) [0x7b545ff27e82]
/usr/local/libexec/../lib/liblagom-core.so.0 Core::EventReceiver::dispatch_event(Core::Event&, Core::EventReceiver*) 0x4d) [0x7b545ff0e12d]
/usr/local/libexec/WebContent(+0x3d797) [0x602ba39c1797]
/usr/lib/libQt6Core.so.6(+0x19b57f) [0x7b5461b9b57f]
/usr/lib/libQt6Core.so.6 QTimer::timerEvent(QTimerEvent*) 0xa5) [0x7b5461ba0d05]
/usr/lib/libQt6Core.so.6 QObject::event(QEvent*) 0x226) [0x7b5461b8c0e6]
/usr/lib/libQt6Core.so.6 QCoreApplication::notifyInternal2(QObject*, QEvent*) 0x133) [0x7b5461b3fdf3]
/usr/lib/libQt6Core.so.6 QTimerInfoList::activateTimers() 0x5c8) [0x7b5461cb7988]
/usr/lib/libQt6Core.so.6(+0x3957c9) [0x7b5461d957c9]
/usr/lib/libglib-2.0.so.0(+0x5ca89) [0x7b545c50ea89]
/usr/lib/libglib-2.0.so.0(+0xbe9b7) [0x7b545c5709b7]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x35) [0x7b545c50df95]
/usr/lib/libQt6Core.so.6 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x89) [0x7b5461d93389]
/usr/local/libexec/WebContent(+0x3d359) [0x602ba39c1359]
/usr/local/libexec/../lib/liblagom-core.so.0 Core::EventLoop::spin_until(AK::Function<bool ()>) 0xbd) [0x7b545ff0707d]
/usr/local/libexec/../lib/liblagom-web.so.0 Web::Platform::EventLoopPluginSerenity::spin_until(JS::SafeFunction<bool ()>) 0x10a) [0x7b5460ae3bba]
/usr/local/libexec/../lib/liblagom-web.so.0 Web::HTML::EventLoop::spin_until(JS::SafeFunction<bool ()>) 0xee) [0x7b5460819f6e]
/usr/local/libexec/../lib/liblagom-web.so.0 Web::HTML::HTMLParser::the_end(JS::NonnullGCPtr<Web::DOM::Document>, JS::GCPtr<Web::HTML::HTMLParser>) 0x3f4) [0x7b5460926154]
/usr/local/libexec/../lib/liblagom-web.so.0 Web::HTML::HTMLParser::run(URL::URL const&, Web::HTML::HTMLTokenizer::StopAtInsertionPoint) 0x2ec) [0x7b546092663c]
/usr/local/libexec/../lib/liblagom-web.so.0(+0xae48d9) [0x7b5460ae48d9]
/usr/local/libexec/../lib/liblagom-core.so.0 Core::ThreadEventQueue::process() 0x3de) [0x7b545ff2788e]
/usr/local/libexec/WebContent(+0x3d91d) [0x602ba39c191d]
/usr/local/libexec/WebContent(+0x3e94c) [0x602ba39c294c]
/usr/lib/libQt6Core.so.6 QCoreApplication::notifyInternal2(QObject*, QEvent*) 0x133) [0x7b5461b3fdf3]
/usr/lib/libQt6Core.so.6 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) 0x362) [0x7b5461b401d2]
/usr/lib/libQt6Core.so.6(+0x3959ac) [0x7b5461d959ac]
/usr/lib/libglib-2.0.so.0(+0x5ca89) [0x7b545c50ea89]
/usr/lib/libglib-2.0.so.0(+0xbe9b7) [0x7b545c5709b7]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x35) [0x7b545c50df95]
/usr/lib/libQt6Core.so.6 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x89) [0x7b5461d93389]
/usr/lib/libQt6Core.so.6 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) 0x1b0) [0x7b5461b48350]
/usr/local/libexec/../lib/liblagom-core.so.0 Core::EventLoop::exec() 0x44) [0x7b545ff071e4]
/usr/local/libexec/WebContent(+0x49c44) [0x602ba39cdc44]
/usr/local/libexec/WebContent(main+0x81) [0x602ba39c0801]
/usr/lib/libc.so.6(+0x25c88) [0x7b545cc39c88]
/usr/lib/libc.so.6(__libc_start_main+0x8c) [0x7b545cc39d4c]
/usr/local/libexec/WebContent(+0x3c9a5) [0x602ba39c09a5]
101277.596 Ladybird(122962): WebContent process crashed!

### PR DESCRIPTION
**Pull request by tcl3**
This PR adds checks to ensure the document's node navigable is not null in `Document::inclusive_ancestor_navigables()`, `Document::inclusive_descendant_navigables` and `Navigable::navigate()`. These null checks aren't explicitly mentioned by the spec, but the spec also doesn't prohibit these methods being called with a null navigable.

Each of these methods previously caused a crash when trying to navigate between pages on https://engadget.com.

Fixes #199

### CODE REVIEW

**Comment by tcl3** [comment]
Hmmm, I'm now intermittently seeing a different crash when navigating betwen pages on engadget.com. Strange that I didn't see it before now :thinking: 

<details><summary>Stack trace</summary>

```
VERIFICATION FAILED: m_ptr at /home/tim/repos/ladybird/Userland/Libraries/LibJS/Heap/GCPtr.h:174
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-ak.so.0(ak_verification_failed+0x8a) [0x70fa1b9a4c03]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0 Web::HTML::Navigable::navigate(Web::HTML::Navigable::NavigateParams) 0x20e) [0x70fa1a4a5a8a]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0 Web::HTML::NavigableContainer::navigate_an_iframe_or_frame(URL::URL, Web::ReferrerPolicy::ReferrerPolicy, AK::Optional<AK::String>) 0x201) [0x70fa1a4aee9d]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0 Web::HTML::HTMLIFrameElement::process_the_iframe_attributes(bool) 0x4b9) [0x70fa1a449337]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0x8493a4) [0x70fa1a4493a4]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0x851b91) [0x70fa1a451b91]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0x8ae068) [0x70fa1a4ae068]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0x8ae12b) [0x70fa1a4ae12b]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0x5a02f9) [0x70fa1a1a02f9]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0x90e389) [0x70fa1a50e389]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0x90e3ad) [0x70fa1a50e3ad]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0(+0x3299f) [0x70fa1bd7c99f]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0 Core::Timer::timer_event(Core::TimerEvent&) 0x33) [0x70fa1bd99d9b]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0 Core::EventReceiver::event(Core::Event&) 0x2b) [0x70fa1bd7bc15]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0 Core::EventReceiver::dispatch_event(Core::Event&, Core::EventReceiver*) 0x7e) [0x70fa1bd7bed6]
/home/tim/repos/ladybird/Build/ladybird/libexec/WebContent(+0x154422) [0x568f29fbb422]
/home/tim/repos/ladybird/Build/ladybird/libexec/WebContent(+0x154774) [0x568f29fbb774]
/home/tim/repos/ladybird/Build/ladybird/libexec/WebContent(+0x154913) [0x568f29fbb913]
/lib/x86_64-linux-gnu/libQt6Core.so.6(+0x183d9b) [0x70fa1bf83d9b]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QTimer::timeout(QTimer::QPrivateSignal) 0x3d) [0x70fa1bf8ed6d]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QObject::event(QEvent*) 0x1c6) [0x70fa1bf76576]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QCoreApplication::notifyInternal2(QObject*, QEvent*) 0xf6) [0x70fa1bf38416]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QTimerInfoList::activateTimers() 0x36b) [0x70fa1c07b7ab]
/lib/x86_64-linux-gnu/libQt6Core.so.6(+0x333a29) [0x70fa1c133a29]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5d5b5) [0x70fa171145b5]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xbc717) [0x70fa17173717]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x70fa17113a53]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x6f) [0x70fa1c1315ef]
/home/tim/repos/ladybird/Build/ladybird/libexec/WebContent(+0x1542d6) [0x568f29fbb2d6]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0 Core::EventLoop::pump(Core::EventLoop::WaitMode) 0x20) [0x70fa1bd74828]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0 Core::EventLoop::spin_until(AK::Function<bool ()>) 0x58) [0x70fa1bd74e76]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0 Web::Platform::EventLoopPluginSerenity::spin_until(JS::SafeFunction<bool ()>) 0x61) [0x70fa1a62c647]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0 Web::HTML::EventLoop::spin_until(JS::SafeFunction<bool ()>) 0xf3) [0x70fa1a418369]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0 Web::HTML::HTMLParser::the_end(JS::NonnullGCPtr<Web::DOM::Document>, JS::GCPtr<Web::HTML::HTMLParser>) 0x350) [0x70fa1a4cc45c]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0 Web::HTML::HTMLParser::run(URL::URL const&, Web::HTML::HTMLTokenizer::StopAtInsertionPoint) 0xe5) [0x70fa1a4dc0e3]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0x73157d) [0x70fa1a33157d]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0x731591) [0x70fa1a331591]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0x851b91) [0x70fa1a451b91]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0xa2ca9d) [0x70fa1a62ca9d]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0(+0x3299f) [0x70fa1bd7c99f]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0 Core::ThreadEventQueue::process() 0x1d1) [0x70fa1bd98857]
/home/tim/repos/ladybird/Build/ladybird/libexec/WebContent(+0x15460a) [0x568f29fbb60a]
/home/tim/repos/ladybird/Build/ladybird/libexec/WebContent(+0x15601e) [0x568f29fbd01e]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QCoreApplication::notifyInternal2(QObject*, QEvent*) 0xf6) [0x70fa1bf38416]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) 0x1a5) [0x70fa1bf38635]
/lib/x86_64-linux-gnu/libQt6Core.so.6(+0x333a8f) [0x70fa1c133a8f]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5d5b5) [0x70fa171145b5]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xbc717) [0x70fa17173717]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x70fa17113a53]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x6f) [0x70fa1c1315ef]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) 0x2e3) [0x70fa1bf429a3]
/home/tim/repos/ladybird/Build/ladybird/libexec/WebContent(+0x15427a) [0x568f29fbb27a]
/home/tim/repos/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0 Core::EventLoop::exec() 0x37) [0x70fa1bd74de9]
/home/tim/repos/ladybird/Build/ladybird/libexec/WebContent(+0x160bb0) [0x568f29fc7bb0]
/home/tim/repos/ladybird/Build/ladybird/libexec/WebContent(main+0x116) [0x568f2a084755]
/lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x70fa16a2a1ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x70fa16a2a28b]
/home/tim/repos/ladybird/Build/ladybird/libexec/WebContent(+0x153975) [0x568f29fba975]
```
</details>

**Comment by kalenikaliaksandr** [comment]
could you add tests for the new null checks?

**Comment by kalenikaliaksandr** [comment]
I think it's fine to add new null-checks without a test, if commit description provides a code-path that hits it. But then, if you know why it happens, you could easily write a test. On the other hand, adding null-checks when we do not even know how to reproduce the problem seems unwise.

**Comment by avbdr** [comment]
@kalenikaliaksandr https://github.com/LadybirdBrowser/ladybird/issues/199 has a 100% manually reproducible crash. Unfortunately i cant provide a reduced test case. :( It seems that the crash happens when during a page load (you click on the link and it starts to load) you start the load of the new page (after some pause you click on a different link and it initiates a new page load).  

Like @tcl3 mentioned  this null checks are not fixing an issue completely but make it to cause different crash in a different place. :)

**Pull request closed without merging**
