### PR TITLE
LibWeb: Use available size in calculate_inner_height()

### PR DESCRIPTION
**Pull request by kalenikaliaksandr**
Although the parameter is named "available size," it is always supposed
to represent the containing block size whenever it has a definite value.
Therefore, it is possible to simply use this value instead of performing
a containing block lookup.

This change actually improves correctness for grid items whose
containing block is defined by the grid area, as
`Node::containing_block()` does not account for this.

### CODE REVIEW

**Comment by awesomekling** [comment]
The first commit says it can’t have a test because it’s preparation for the second commit.

But the second commit has no test either? :)

**Comment by kalenikaliaksandr** [comment]
> he first commit says it can’t have a test because it’s preparation for the second commit.
> 
> But the second commit has no test either? :)

right, the first commit is needed to avoid regression in the second. and the second is needed to avoid containing block lookup and align calculate_inner_height() with calculate_inner_width(), so both use passed available size.

**Comment by awesomekling** [comment]
> > he first commit says it can’t have a test because it’s preparation for the second commit.
> > But the second commit has no test either? :)
> 
> right, the first commit is needed to avoid regression in the second. and the second is needed to avoid containing block lookup and align calculate_inner_height() with calculate_inner_width(), so both use passed available size.

This part of the commit message made it sound testable:

> This change actually improves correctness for grid items whose
containing block is defined by the grid area, as
`Node::containing_block()` does not account for this.

So it’s more correct now but not in a way we can prove with a test?

**Comment by kalenikaliaksandr** [comment]
ok, that's fair! I added new test that demoes improvement in correctness. it was actually easier than I though 😅

**Pull request merged**
