### PR TITLE
LibWeb/ARIA: Add missing structure roles

### PR DESCRIPTION
**Pull request by Simek**
# Why

* https://wpt.fyi/results/wai-aria/role/roles.html?product=ladybird&product=chrome&q=aria
* https://www.w3.org/TR/wai-aria-1.2/#document_structure_roles

# How

Add missing `code` and `superscript` roles to structure roles list.

Make sure that correct accessibility role is set but running test DOM locally and verifying with build-in inspector.

# Preview

Screenshot 2024-12-09 at 00 49 16

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
Non-maintainer LGTM ✅

But as with https://github.com/LadybirdBrowser/ladybird/pull/2842, if possible, could you also import the http://wpt.live/wai-aria/role/roles.html test, and commit the imported test and the corresponding test expectations as part of this PR?
```
./Meta/WPT.sh import http://wpt.live/wai-aria/role/roles.html \
    && git add Tests/LibWeb/Text/input/wpt-import/wai-aria/role/roles.html \
    && git add Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/roles.txt
```

**Comment by trflynn89** [comment]
LGTM as well, but yes, please import the WPT test

**Comment by sideshowbarker** [comment]
@Simek You should be able to import the WPT using the invocation I mentioned earlier:

```
./Meta/WPT.sh import http://wpt.live/wai-aria/role/roles.html \
    && git add Tests/LibWeb/Text/input/wpt-import/wai-aria/role/roles.html \
    && git add Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/roles.txt
```

Please try it. And you have some problem with it, lemme or somebody else know, and we can figure how to get it working for you

**Comment by Simek** [comment]
The problem here is that test is not working correctly on WPT, nor locally, after downloading. There are some issue in test harness file, so it's not related to Ladybird in any way:

* https://wpt.live/wai-aria/role/roles.html - it fails internally when running on WPT
  Screenshot 2024-12-11 at 14 16 10  

* it fails in the same way after downloading locally:
  Screenshot 2024-12-11 at 14 10 41

That's why I have did not import the test initially, since it would only generate false failures. So I have decided to recreate test DOM locally, and verify the roles manually instead.

If you think that there is a value in committing the test in that state, LMK, I will add the files.

**Comment by Simek** [comment]
After rebase, the test still fails for me locally, but with a slightly different error:

Screenshot 2024-12-11 at 16 12 57

**Comment by tcl3** [comment]
> After rebase, the test still fails for me locally, but with a slightly different error:

The imported test should pass when run in the browser, if you launch the browser with the `--expose-internals-object` option.

**Comment by Simek** [comment]
That was the part I was missing, hence the question about how to run locally, thanks @tcl3! 👍 

Just pushed the imported test, and correct expected output.

**Comment by trflynn89** [comment]
The new test should be squashed into the first commit
(FYI the reason the commit linter fails is because the first word after the category must be capitalized, but in this case, it makes most sense for the test to be in the first commit).

**Comment by trflynn89** [comment]
Also for future reference, you can also run the test in our headless browser, which is what CI will do. The follow command will run the test with the appropriate flags (the -f flag is a filter for the imported test):
```bash
./Meta/ladybird.sh run headless-browser --run-tests ./Tests/LibWeb -f role/roles.html
```

**Review by trflynn89 — APPROVED** [review]
Thanks for sticking with this!

**Pull request merged**
