### PR TITLE
UI/Qt: Set dark theme as reported by Qt

### PR DESCRIPTION
**Pull request by shlyakpavel**
Previously, we did a bit of guessing.
That approach was hacky and less reliable.

### CODE REVIEW

**Comment by yyny** [comment]
Nit:

> That approach ***was*** hacky and less reliable.

**Review by tcl3 — COMMENTED** [review]
This doesn't compile for me. According to [the docs](https://doc.qt.io/qt-6/qstylehints.html#colorScheme-prop) this property was added in 6.5. On Ubuntu I have 6.4.2 installed.

It looks like we do use `#if (QT_VERSION > QT_VERSION_CHECK(major, minor, patch))` elsewhere in the code, so you could use that to ensure you only use the built in way of doing things if the QT_VERSION is new enough.

**Comment by shlyakpavel** [comment]
@tcl3 elsewhere, we're using QT_VERSION_CHECK(6, 6, 0) and higher. Are you sure it's a good idea to support ancient Qt versions?

**Review by tcl3 — APPROVED** [review]
This works very nicely on MacOS (with Qt 6.7), where the page will now update live in response to changes in the system color theme :tada:

**Pull request merged**
