### PR TITLE
Meta: Switch to clang-19 and clang-format-19

### PR DESCRIPTION
**Pull request by trflynn89**
clang 19 has been out for some time, and it's becoming increasingly difficult to keep clang-format-18 on updated distros.

### CODE REVIEW

**Comment by ADKaster** [comment]
I think for the next transition we should think about yeeting our clang-format script and just relying on `git clang-format`

**Comment by trflynn89** [comment]
:man_shrugging: Despite the authors of clang-format disagreeing, I prefer just doing a project-wide reformat on a code base of our size

**Comment by shannonbooth** [comment]
> 🤷‍♂️ Despite the authors of clang-format disagreeing, I prefer just doing a project-wide reformat on a code base of our size

Yeah, agree, from experience incremental format is more painful than a one that does the entire thing

**Comment by ADKaster** [comment]
>  🤷‍♂️ Despite the authors of clang-format disagreeing, I prefer just doing a project-wide reformat on a code base of our size

Fair enough. Certainly not a hill I'm willing to die on.

**Pull request merged**
