### PR TITLE
LibGC+Everywhere: Factor out a LibGC from LibJS

### PR DESCRIPTION
**Pull request by shannonbooth**
Resulting in a massive rename across almost everywhere! Alongside the namespace change, we now have the following names:

 * `JS::NonnullGCPtr` -> `GC::Ref`
 * `JS::GCPtr` -> `GC::Ptr`
 * `JS::HeapFunction` -> `GC::Function`
 * `JS::CellImpl` -> `GC::Cell`
 * `JS::Handle` -> `GC::Root`

### CODE REVIEW

**Comment by ADKaster** [comment]
Looks like you need to
1. update the expectations in the clang plugin tests
2. link LibGC to FuzzJS

**Comment by shannonbooth** [comment]
Hmm @ADKaster  where do I need to add the linking for FuzzJS? I have it here currently: https://github.com/shannonbooth/ladybird/blob/f4aa504cfd282185a2b5b741fd9fd805c54427a3/Meta/Lagom/Fuzzers/CMakeLists.txt#L45

**Comment by shannonbooth** [comment]
> Hmm @ADKaster where do I need to add the linking for FuzzJS? I have it here currently: https://github.com/shannonbooth/ladybird/blob/f4aa504cfd282185a2b5b741fd9fd805c54427a3/Meta/Lagom/Fuzzers/CMakeLists.txt#L45

Ah nevermind, I think I found it

**Comment by awesomekling** [comment]
Okay let's rip off the bandaid

**Pull request merged**
