### PR TITLE
LibCore: Port DirIterator to Windows using vcpkg dirent.h

### PR DESCRIPTION
**Pull request by stasoid**
This PR implements a cleaner port of DirIterator using dirent.h for Windows provided by vcpkg in `Build\ladybird\vcpkg_installed\x64-windows\include`. This `dirent.h` includes windows.h, so I don't include it in header files on Windows.

### CODE REVIEW

**Comment by ADKaster** [comment]
This is super interesting. However, it seems a bit awkward to not declare a direct dependency on the specific package that is providing dirent.h

Grepping on my linux machine, it looks like it could be provided by libjxl?

```
$ find Toolchain/Tarballs/vcpkg/ -name "dirent.h"
Toolchain/Tarballs/vcpkg/buildtrees/libjxl/src/v0.11.0-242a572c17.clean/third_party/dirent.h
```

I'm not sure that pulling in this libjxl specific wrapper is better than using our own implementation that does the same thing. Especially given how simple their version is.

<https://github.com/libjxl/libjxl/blob/main/third_party/dirent.cc>

Though this file's dirent.h doesn't include windows.h from the top level :thinking:

**Comment by stasoid** [comment]
This is dirent.h from package [dirent](https://github.com/tronkko/dirent):
`Toolchain\Tarballs\vcpkg\packages\dirent_x64-windows\include\dirent.h`
`Toolchain\Tarballs\vcpkg\buildtrees\dirent\src\1.24-cd31aecacf.clean\include\dirent.h`

It is quite popular, the first result of google\<dirent for windows>. I used it in other projects.

I didn't use `target_link_libraries(LibCoreMinimal PRIVATE dirent)` because it doesn't work for some reason (`fatal  error : 'dirent.h' file not found`).

**Comment by ADKaster** [comment]
If we intend to use dirent-the-package directly, then we should add it to vcpkg.json explicitly for windows. This does simplify the functionality a lot, so +1 from me.

**Comment by stasoid** [comment]
Added dirent to vcpkg.json. `target_link_libraries(LibCoreMinimal PRIVATE dirent)` still doesn't work, so keeping `target_include_directories`.

**Review by ADKaster — APPROVED** [review]

**Pull request merged**
