### PR TITLE
CI: Configure stale bot for PRs

### PR DESCRIPTION
**Pull request by gmta**
We want to remind both contributors and maintainers that PRs should be up-to-date, reviewed and merged. Stale bot does a pretty good job of notifying the right people :^)

### CODE REVIEW

**Comment by rmg-x** [comment]
I believe it's possible to exempt draft PRs with `exempt-draft-pr: true` if we wanted to do that.

https://github.com/actions/stale?tab=readme-ov-file#exempt-draft-pr

**Comment by gmta** [comment]
> I believe it's possible to exempt draft PRs with `exempt-draft-pr: true` if we wanted to do that.

Why would we add an exception for drafts?

**Comment by rmg-x** [comment]
Drafts to me indicate that there may be external blockers (e.g. spec updates or research) so having to worry about stalebot might be a bit annoying. But, some drafts don't fit that category either and just sit for no reason.

Not really an issue either way, but thought I'd point it out in-case maintainers found it useful.

**Comment by gmta** [comment]
> Drafts to me indicate that there may be external blockers (e.g. spec updates or research)

Right, that happens sometimes, but we also have a lot of blocked drafts that never get any followup. Stalebot is useful in that sense to keep drafts alive and relevant, imo.

**Comment by stelar7** [comment]
Having PRs be auto-closed after 30 days seems somewhat bad, especially if the PR is "done", and only waiting for review / merge by a maintainer

**Comment by gmta** [comment]
> Having PRs be auto-closed after 30 days seems somewhat bad, especially if the PR is "done", and only waiting for review / merge by a maintainer

That's the goal of stalebot: if it just needs a review or merge, we should be reminded with a somewhat looming deadline.

**Comment by stelar7** [comment]
> That's the goal of stalebot: if it just needs a review or merge, we should be reminded with a somewhat looming deadline. Not everyone uses `#code-review` and not all maintainers peruse the PR list continuously.

Yes, but from experience with it in Serenity, it got to the point a good few times 😅

**Comment by AtkinsSJ** [comment]
The alternative to Stalebot is what we have now: pages of PRs that are months old and forgotten about.

It's not perfect and we're open to better solutions, but the current setup really isn't working, and Stalebot would be a big improvement.

**Comment by circl-lastname** [comment]
> > That's the goal of stalebot: if it just needs a review or merge, we should be reminded with a somewhat looming deadline. Not everyone uses `#code-review` and not all maintainers peruse the PR list continuously.
> 
> Yes, but from experience with it in Serenity, it got to the point a good few times 😅

Then you can Bump your own PR (which removes the stale label and resets the 30 day counter) and post it in code-review as a reminder

**Comment by gmta** [comment]
Let's merge this and let the reaping begin!

**Comment by ronak69** [comment]
Instead of auto-closing, can it just post another message to remind everyone? I see zero benefit of auto-closing and to me it is incredibly annoying.

**Comment by circl-lastname** [comment]
If you do not want it to close you can leave a comment. It will remove the stale label and reset the timeout (at least that's how it worked back in the SerenityOS days). It will also do so if you rebase the branch onto master, which will fix the merge conflicts that may develop over the course of 37 days, allowing the PR to be actually reviewed. If the author has no interest about the PR after 37 days, allowing it to go to a likely unmergeable state, only then it will be closed.

**Comment by ronak69** [comment]
> If you do not want it to close you can leave a comment.

Or if i wanted to close i would just close.

If the author has no interest about the PR they wouldn't have opened it in the first place.

“A computer can never be held accountable, therefore a computer must never make a management decision.”

**Comment by circl-lastname** [comment]
They can lose interest after opening it. As has happened for many PRs here

**Comment by ADKaster** [comment]
The point of stalebot is to give both maintainers and contributors more opportunities (and distinct gates) to get emails/notifications about the PR. It forces action to either say "oh yeah, I didn't care about this change" or to say "hey, this needs review!" and get a maintainer to look at it with a message/ping in #code-review. Because we do feel bad when a PR with good changes drops off the radar. It also acts as an opportunity for contributors to say "oh, I don't have time to work on this change", which allows other contributors or the maintainers to commandeer the PR to get a new revision of the patch up for review.

**Pull request merged**
