### PR TITLE
LibGfx: Don't try to paint glyphs that aren't in a font

### PR DESCRIPTION
**Pull request by awesomekling**
Fixes https://github.com/LadybirdBrowser/ladybird/issues/88

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Should this try to draw the "missing character" symbol instead? Or is that already handled somewhere else.

**Comment by awesomekling** [comment]
> Should this try to draw the "missing character" symbol instead? Or is that already handled somewhere else.

If we wanted to draw the "missing character", we should have figured that out much earlier and asked to draw the missing character glyph :)

**Comment by awesomekling** [comment]
If we didn't choose the missing character glyph earlier, we most likely think whatever we're drawing will fit into 0x0 space as well :sweat_smile:

**Comment by AtkinsSJ** [comment]
Yeah I'm just a little confused how we end up here without a valid glyph. It's fine as a "just in case" check, it's just odd that we're hitting it.

**Pull request merged**
