### PR TITLE
LibWeb: Add coverage test for calc() usage

### PR DESCRIPTION
**Pull request by AtkinsSJ**
As can be seen from the output, we're missing full `calc()` support for the following properties:

- [ ] grid-auto-columns
- [ ] grid-auto-rows
- [ ] grid-template-columns
- [ ] grid-template-rows
- [ ] transform-origin

~~The `grid-*` ones seem to just be missing a `getComputedStyle` implementation, so it's hard to tell.~~ I found the bug, it's fixed in a commit here.

### CODE REVIEW

**Review by tcl3 — COMMENTED** [review]
The change itself looks fine to me but is "fuzzing test" the best term for this? I'd expect fuzzing to test a feature using many different values, which isn't what this is doing.

Maybe [smoke test](https://en.wikipedia.org/wiki/Smoke_testing_(software)) or functionality test would be clearer?

**Comment by AtkinsSJ** [comment]
True. I also realised while having lunch that this doesn't properly test things, because anything with var() in (which I added to stop it immediately being simplified) has its calc()s resolved in a different code path. So I'll rewrite it to try each property multiple times with different values instead.

Removing that path doesn't make us fail any of our tests but does mean we serialise calc() values verbatim instead of simplified, so we'll fail a bunch of WPT tests. I really ought to get simplification done.

**Comment by AtkinsSJ** [comment]
Changes:
- Add test cases that don't use `var()`.
- Rename the test.
- Add in a fix for `grid-template-*` properties serializing to the empty string.

**Comment by AtkinsSJ** [comment]
Rebased because I merge-conflicted myself with the `grid-*-gap` change. :laughing:

**Comment by AtkinsSJ** [comment]
Just corrected the commit message, there were a couple more properties I hadn't noticed I'd fixed. :laughing:

**Pull request merged**
