### PR TITLE
LibJS: Make function instantiation a bit more spec compliant

### PR DESCRIPTION
**Pull request by mobounya**
We used to call `ECMAScriptFunctionObject::create()` to instantiate different types of JS functions with a lot of "prep" hidden in `ECMAScriptFunctionObject::initialize()`. This replaces that with `instantiate_function_object()` which matches the specs and organizes function initialization in one place.

To be safe I choose to skip the code in `ECMAScriptFunctionObject::initialize()` if we're instantiation from a   `instantiate_function_object()` otherwise that code will be executed since `ECMAScriptFunctionObject::create()` is called from a bunch of other places that may need it. I think ideally that code should be removed and JS function initialization should be done from functions that match the specs.

test262 diff:
```
None
```

### CODE REVIEW

**Comment by awesomekling** [comment]
Typo: seperate -> separate

A valuable optimization we should do is moving everything immutable from `ECMAScriptFunctionObject` that doesn't change between instantiations and caching it in a shared object, held by the AST node.

This would make instantiation much faster, since we could reuse all the shared data instead of recomputing it. :)

**Comment by mobounya** [comment]
@awesomekling is there anything else that we can cache in `ECMAScriptFunctionObject` that I'm missing :thinking: ?

**Comment by kalenikaliaksandr** [comment]
have you checked how this change affects test262?

**Comment by mobounya** [comment]
@kalenikaliaksandr I've included the test262 diff

**Comment by mobounya** [comment]
Apparently what I thought are improvement to the test262 results are just my machine being slow at times and fast at times, so no changes to the test262

**Pull request closed without merging**
