### PR TITLE
LibWeb: Block file: and resource: URLs on websites (and make resource: work on file: pages)

### PR DESCRIPTION
**Pull request by circl-lastname**
This makes icons once again load in the directory listings
Screenshot at 2024-06-10 12-35-28

### CODE REVIEW

**Comment by trflynn89** [comment]
IMO resource:// URLs should be protected and not generally available. i.e. randomwebsite.com should not be allowed to load a resource:// URL.

We should either A) recognize when a page is an internal browser page and allow them to use resource:// URLs, or B) have whatever generates the directory page map resource:// URLs to file:// URLs

**Comment by circl-lastname** [comment]
file:// schemes are similarly blocked by the CORS mechanism so it could be added to that

**Comment by circl-lastname** [comment]
Hm - about: is actually not allowed to access file:// but *is* allowed to access resource://. Would explicitly allowing about: access to resource:// work?

**Comment by circl-lastname** [comment]
Apparently they are not???

**Comment by circl-lastname** [comment]
I've added a check for opaque, file: and resource: schemes when trying to access file: or resource:

**Review by ADKaster — APPROVED** [review]

**Pull request merged**
