### PR TITLE
SVG: Add support for fetching SVG use elements from external documents

### PR DESCRIPTION
**Pull request by shannonbooth**
This allows SVG <use> elements to refer to elements which are in other
documents, such as https://www.neogaf.com/forums/gaming-discussion.2/
or Lemmy.ml

Fixes: https://github.com/LadybirdBrowser/ladybird/issues/141
Progress towards: https://github.com/LadybirdBrowser/ladybird/issues/350

image

### CODE REVIEW

**Review by tcl3 — COMMENTED** [review]
Looking at some of the relevant WPT tests for this, I noticed one small thing. With this change we now pass: https://wpt.live/svg/struct/reftests/use-external-html-resource-with-content-type-svg.html, but we don't pass: https://wpt.live/svg/struct/reftests/use-external-html-resource.html. 

Would it be possible to make this work with files that have a HTML MIME type too?

**Comment by shannonbooth** [comment]
> Looking at some of the relevant WPT tests for this, I noticed one small thing. With this change we now pass: https://wpt.live/svg/struct/reftests/use-external-html-resource-with-content-type-svg.html, but we don't pass: https://wpt.live/svg/struct/reftests/use-external-html-resource.html.
> 
> Would it be possible to make this work with files that have a HTML MIME type too?

Yup! Will look at it, but may be a few days before I get around to it. I suppose SharedImageRequest may bot be appropriate and would need to change to something else (or adjust it).

**Comment by shannonbooth** [comment]
image
I've got it working ontop of this branch - but still figuring out some kinks.

Seems like that test doesn't work on firefox or chrome - maybe can be left for a follow up?

**Comment by shannonbooth** [comment]
CI failure looks like an unrelated flake

**Pull request merged**
