### PR TITLE
AK: Add generic SIMD shuffle/reverse functions

### PR DESCRIPTION
**Pull request by alimpfard**
(cherry picked from commit 1b8fd5c35afda8f797f1e8a39c332fa14950006e)

cc @Hendiadyoin1.

### CODE REVIEW

**Comment by Hendiadyoin1** [comment]
Ooops I think the AK ones are the wrong way around,
(Also note that the code got slightly better with dans PR, regarding __builtin_bitcast shenanigans)

**Comment by alimpfard** [comment]
lol oops

**Comment by DanShaders** [comment]
> Also note that the code got slightly better with dans PR

SerenityOS/serenity@56b7f9e404429017a4894a9d9d173a389eb71a40 and SerenityOS/serenity@2b65b62c6e58d8a00ac991a47b9b0e6197f790b4

**Comment by alimpfard** [comment]
I'm not sure if disabling -Wpsabi globally is safe to do in here; there _are_ other libraries.
I'll pull the bit_cast commit in though.

**Pull request merged**
