### PR TITLE
LibWeb: Scroll page and nav history with keyboard

### PR DESCRIPTION
**Pull request by alec3660**
This patch implements basic keyboard functionality for page scrolling and history traversal.

### CODE REVIEW

**Comment by awesomekling** [comment]
This looks like it would break the ability for JavaScript to detect arrow key presses?

**Comment by alec3660** [comment]
> This looks like it would break the ability for JavaScript to detect arrow key presses?

I tested with the JavaScript snippet below, which appears to be working:

```
<script>
document.onkeydown = function(e) {
    switch (e.keyCode) {
    case 37:
        alert('Left arrow key pressed');
        break;
    case 38:
        alert('Up arrow key pressed');
        break;
    case 39:
        alert('Right arrow key pressed');
        break;
    case 40:
        alert('Down arrow key pressed');
        break;
    }
}
</script>
```

js-arrow-key-test

**Comment by awesomekling** [comment]
And what about the `keypress` event?

**Comment by alec3660** [comment]
> And what about the `keypress` event?

My understanding is the `keypress` event is not fired for these keys, as they do not produce a character value. I tested with Firefox and Chrome, and the result was the same as Ladybird.

**Comment by alec3660** [comment]
However, the space key _does_ produce a character value, so I have removed it from this PR as to not interfere with `keypress` events.

**Comment by awesomekling** [comment]
I'm not 100% confident that there isn't some flaw in this approach, but since it's such a nice QoL upgrade let's just do it anyway for now.

**Pull request merged**
