### PR TITLE
LibWeb/Geometry: Implement "other than none" keyword check in DOMMatrix init

### PR DESCRIPTION
**Pull request by tannerdrake-dev**
This implementation leads to passing more WPT tests. Relevant test imported in this PR.

### CODE REVIEW

**Comment by tcl3** [comment]
Hi, thanks for working on this! The change itself looks OK to me, but we try to avoid adding commits that modify work done in previous commits. All the changes made in this PR should be squashed into the first commit, then I think this should be good to go. Feel free to ask on Discord if you need help with this.

**Comment by tannerdrake-dev** [comment]
> Hi, thanks for working on this! The change itself looks OK to me, but we try to avoid adding commits that modify work done in previous commits. All the changes made in this PR should be squashed into the first commit, then I think this should be good to go. Feel free to ask on Discord if you need help with this.

Thanks for the review. I have squashed the commits down to one as requested.

**Comment by gmta** [comment]
Your commit message is now an amalgamation of the individual commit titles that existed before the squash. You should write a [proper commit message](https://github.com/LadybirdBrowser/ladybird/blob/master/CONTRIBUTING.md#code-submission-policy) instead.

**Comment by tannerdrake-dev** [comment]
> Your commit message is now an amalgamation of the individual commit titles that existed before the squash. You should write a [proper commit message](https://github.com/LadybirdBrowser/ladybird/blob/master/CONTRIBUTING.md#code-submission-policy) instead.

Commit message has been updated to just the proper original message.

**Review by gmta — APPROVED** [review]

**Pull request merged**
