### PR TITLE
Meta: Use dynamic vcpkg linkage for release builds

### PR DESCRIPTION
**Pull request by trflynn89**

### CODE REVIEW

**Comment by ADKaster** [comment]
I rebased this and bumped the simdutf version, hopefully this satisfies the github action cache enough to let this move forward and unblock Alex's GPU work

**Comment by ADKaster** [comment]
Pushed a workaround for https://github.com/microsoft/vcpkg/issues/41971

**Comment by ADKaster** [comment]
Let's go with this and deal with the fallout. :marge:

**Comment by linusg** [comment]
This seems to have broken the artifact created by `ladybird-js-artifacts.yml` (affecting any esvu-installed js(1), e.g. https://github.com/boa-dev/data/actions/runs/11734525189/job/32690696943). https://www.google.com/search?q=%22libsimdutf.so.11%22 suggests that I can install it by hand only on FreeBSD and Alpine so it should probably be shipped alongside liblagom.

```
./bin/js: error while loading shared libraries: libsimdutf.so.11: cannot open shared object file: No such file or directory
```

```console
$ cd ladybird-js-Linux-x86_64
$ ls lib
liblagom-ak.so             liblagom-coreminimal.so.0.0.0  liblagom-js.so.0         liblagom-syntax.so           liblagom-unicode.so.0.0.0
liblagom-ak.so.0           liblagom-crypto.so             liblagom-js.so.0.0.0     liblagom-syntax.so.0         liblagom-url.so
liblagom-ak.so.0.0.0       liblagom-crypto.so.0           liblagom-line.so         liblagom-syntax.so.0.0.0     liblagom-url.so.0
liblagom-core.so           liblagom-crypto.so.0.0.0       liblagom-line.so.0       liblagom-textcodec.so        liblagom-url.so.0.0.0
liblagom-core.so.0         liblagom-filesystem.so         liblagom-line.so.0.0.0   liblagom-textcodec.so.0      
liblagom-core.so.0.0.0     liblagom-filesystem.so.0       liblagom-regex.so        liblagom-textcodec.so.0.0.0  
liblagom-coreminimal.so    liblagom-filesystem.so.0.0.0   liblagom-regex.so.0      liblagom-unicode.so          
liblagom-coreminimal.so.0  liblagom-js.so                 liblagom-regex.so.0.0.0  liblagom-unicode.so.0        
$ ldd bin/js | grep '=> not found' | grep -v 'libstdc++'
	libsimdutf.so.11 => not found
	libicui18n.so.74 => not found
	libicuuc.so.74 => not found
$
```

**Comment by linusg** [comment]
Also affects test262.fyi: https://github.com/test262-fyi/test262.fyi/actions/runs/11733811717/job/32688786826

**Comment by trflynn89** [comment]
Should be fixed by #2225

**Pull request merged**
