### PR TITLE
BindingsGenerator+HTML: Partially implement HTMLInputElement's selection{Start,End}

### PR DESCRIPTION
**Pull request by shannonbooth**
Get the functionality we already have working in HTMLTextAreaElement put into a common place for use in HTMLInputElement.

### CODE REVIEW

**Comment by trflynn89** [comment]
@shannonbooth The new test added here is flaky on master:
```diff
 --- /home/runner/work/ladybird/ladybird/Tests/LibWeb/Text/expected/./input-selection-start-selection-end.txt
+++ /home/runner/work/ladybird/ladybird/Tests/LibWeb/Text/expected/./input-selection-start-selection-end.txt
@@ -1,5 +1,5 @@
-Well hello friends    text selectionStart: 0
-text selectionEnd: 0
+Well hello friends    text selectionStart: 5
+text selectionEnd: 5
 date selectionStart: null
 date selectionEnd: null
 text selectionStart: 18
```

https://github.com/LadybirdBrowser/ladybird/actions/runs/10196223641/job/28206559460

**Comment by nico** [comment]
> @shannonbooth The new test added here is flaky on master:

Was this ever resolved?

**Comment by nico** [comment]
(I suppose #1193 deleted the test again  – I mean before then :))

**Comment by trflynn89** [comment]
> Was this ever resolved?

Yep, the issue was the test was affected by a cursor position retained from the previous test/page load. Fixed in https://github.com/LadybirdBrowser/ladybird/pull/932.

**Pull request merged**
