### PR TITLE
Ladybird: Replace the new tab page with a dark mode friendly blank page

### PR DESCRIPTION
**Pull request by trflynn89**
A giant white about:blank page was killing my eyes 🙃 

Screenshot 2024-06-26 at 9 04 05 AM

### CODE REVIEW

**Comment by jamierocks** [comment]
Would it not make sense to change `about:blank` to do this, rather than `about:newtab` (if it doesn't already)?

I do think that `about:newtab` could do with being spruced up (including dark mode support) however.

**Comment by awesomekling** [comment]
> I think @tcl3 has a patch that makes about:blank honor dark mode

…although messing with the default appearance of about:blank seems risky, since there are probably websites out there that expect it to always be white for some reason…

**Comment by trflynn89** [comment]
Yeah, I mentioned in the commit message that most other browsers leave about:blank as a white page. I figured there's a reason for that.

**Comment by AtkinsSJ** [comment]
It should probably use `Canvas`, right? https://www.w3.org/TR/css-color-4/#valdef-color-canvas

Maybe it does, I haven't checked. Or maybe we just don't have different colours for dark mode.

**Comment by trflynn89** [comment]
Canvas is always white:
https://github.com/LadybirdBrowser/ladybird/blob/848ec538c62594c783032008615abf4a732ed366/Userland/Libraries/LibWeb/CSS/SystemColor.cpp#L41-L44

**Comment by lukewarlow** [comment]
I think this should ideally use Canvas and use the color scheme meta tag to make it honour the underlying theme. So it shouldn't really need the media query at all. But I don't think ladybird has color scheme yet (probably explains why the system colours aren't theme dependent)

**Comment by trflynn89** [comment]
Yes, we have existing FIXMEs about using color schemes when they are supported. I copied that FIXME here.

https://github.com/LadybirdBrowser/ladybird/blob/e800605ad3e4e9dfdc320c137e1beef1a66d2eb0/Userland/Libraries/LibWebView/SourceHighlighter.h#L27-L31

**Comment by tcl3** [comment]
> I think @tcl3 has a patch that makes about:blank honor dark mode

I made a start on a patch to make the `Canvas` and `CanvasText` colors honor the current color theme.

https://github.com/tcl3/ladybird/tree/prevent-user-blindness

After looking into it a bit more though, I'm not sure this is the correct approach, as the `Canvas` and `CanvasText` colors don't automatically change in this way for HTML documents in other browsers. Doing something like this is useful when viewing plain text documents and other non-HTML formats though. The above branch also only respects the current system theme, not the browser color theme.

I'd also echo what Andreas said about changing `about:blank` not necessarily being a wise idea. The Firefox `about:blank` does honor dark mode, but Chrome's does not.

**Comment by AtkinsSJ** [comment]
[The spec](https://www.w3.org/TR/css-color-4/#css-system-colors) does give us a lot of freedom for whether to customise those colours and what to set them to.  Fingerprinting is mentioned, but we're already an obscure browser so that won't make much difference. 😅

My vote is to go ahead with making it adapt to dark mode.

**Comment by circl-lastname** [comment]
> …although messing with the default appearance of about:blank seems risky, since there are probably websites out there that expect it to always be white for some reason…

Firefox only makes about:blank dark if it's opened in a tab, any other uses make it white

**Comment by awesomekling** [comment]
Sure, let's roll with this for now :)

**Pull request merged**
