### PR TITLE
LibWeb: Ensure normal line-height on inputs and remove unused method

### PR DESCRIPTION
**Pull request by rmg-x**

### CODE REVIEW

**Comment by rmg-x** [comment]
Found on https://pcpartpicker.com/list/

Before:
image

After:
image

**Comment by awesomekling** [comment]
Looks like a good-enough fix, but please add a test. :)

Also, please wrap commit messages at 72 characters, not 50 or whatever this is.

**Comment by rmg-x** [comment]
> Looks like a good-enough fix, but please add a test. :)
> 
> Also, please wrap commit messages at 72 characters, not 50 or whatever this is.

Sure, where would a test go for this kind of change?

**Comment by rmg-x** [comment]
@awesomekling This PR is ready for review again. Commit messages are wrapped and tests are passing :)

**Pull request merged**
