### PR TITLE
Everywhere: Hoist everything out of the Userland directory

### PR DESCRIPTION
**Pull request by trflynn89**
There's no particularly good time to do this, but this gets rid of the Userland and Ladybird directories. For the former, Libraries+Services+Utilities are hoisted to the top-level directory. For the latter, the Ladybird directory is renamed to UI, as we've been using UI as the commit category for these files.

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
FWIW I can report that I checked out this PR branch and tried it in my local (macOS) environment — did some builds, ran some tests, checked LSP behavior in my editor — and everything worked for me as expected.

**Comment by awesomekling** [comment]
All right, let's just pull off the band-aid :)

**Comment by stasoid** [comment]
Maybe also move AK to Libraries?

**Comment by Gingeh** [comment]
just noticed the GN build files haven't been updated to reflect this change

**Pull request merged**
