### PR TITLE
LibWeb/CSS: Add support for the `srgb-linear` color space in `color()`

### PR DESCRIPTION
**Pull request by LucasChollet**
That makes us pass the following WPT tests:
 - css/css-color/srgb-linear-001.html
 - css/css-color/srgb-linear-002.html
 - css/css-color/srgb-linear-003.html

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Code looks fine. Can we get those other tests imported too?

**Comment by LucasChollet** [comment]
I can add them, no problem. Generally, what's the policy regarding WPT imports? Should I import all of the test that I made passing? I always assumed that I should not import all of them to avoid bloating our internal test suite and making it takes hours to complete.

Also if I was to add more than one test for this color space, should I also add more for other color spaces? If so, can I do it in a follow up? I already have a PR waiting that is depending on this one.

**Comment by AtkinsSJ** [comment]
> I can add them, no problem. Generally, what's the policy regarding WPT imports? Should I import all of the test that I made passing? I always assumed that I should not import all of them to avoid bloating our internal test suite and making it takes hours to complete.

If they're slow, then avoid them, but generally we're importing as many as possible to get good coverage. (And they run much faster in our own test suite than they do using proper WPT.) Tim's been working on a way to mass-import whole directories at once.

> Also if I was to add more than one test for this color space, should I also add more for other color spaces? If so, can I do it in a follow up? I already have a PR waiting that is depending on this one.

Yes please! And sure, later is fine.

**Comment by awesomekling** [comment]
> I can add them, no problem. Generally, what's the policy regarding WPT imports? Should I import all of the test that I made passing? I always assumed that I should not import all of them to avoid bloating our internal test suite and making it takes hours to complete.
> 
> Also if I was to add more than one test for this color space, should I also add more for other color spaces? If so, can I do it in a follow up? I already have a PR waiting that is depending on this one.

For importing WPT tests, anything that offers more coverage and isn’t comically slow is a good candidate for import IMO :)

**Comment by LucasChollet** [comment]
Oops, I guess I got a proof of why it's good to import tests. The issue with `srgb-linear-004.html` is in our conversion from XYZ (both D50 and D65) to sRGB, should we proceed with this PR and just drop the faulty test or do you guys want to wait for me to fix it?

**Pull request merged**
