### PR TITLE
LibWeb: Update cursor + fire mouse events while scrolling

### LINKED ISSUE #452: "onmouseenter" event doesn't trigger when cursor is stationery and content move underneath it.
This works correctly on FF and chrome. See below video on comparison of FF (left), Chrome (center) and Ladybird (right).

https://github.com/LadybirdBrowser/ladybird/assets/31415645/c4552df3-dd44-45b5-a341-e5c89b84e29f

---

### According to W3C UI events spec:

[Link to "event-type-mouseenter" spec](https://w3c.github.io/uievents/#event-type-mouseenter).

image

---

### Minimal reproduction code: 

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    h1 {
      color: red;
    }
    body {
      display: flex;
      flex-direction: column;
      gap: 3rem;
      padding: 5rem;
      background-color: darkslategray;
    }
    div {
      width: 300px;
      height: 100px;
      background-color:darkkhaki;
      font-size: larger;
      display: flex;
      justify-content: center;
      align-items: center;
    }
    div#imp {
        background-color: hotpink;
    }
  </style>
</head>
<body>
  <div></div>
  <div 
    id="imp"
    onmouseenter="console.log('mouse enter event')"
  > 
    mouse enter/exit event on this div
  </div>
  <div></div>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by 0GreenClover0**
Previously, the cursor and events would only be updated and fired when moving the mouse.

Fixes partially #452.

| Before | After |
| --- | --- |
| <video src="https://github.com/LadybirdBrowser/ladybird/assets/36564831/9ea57b4f-bcd1-4446-a20c-093e47f51d24"> | <video src="https://github.com/LadybirdBrowser/ladybird/assets/36564831/fdbf6fb8-f6ef-4e7a-9800-62acf518e885"> |

### CODE REVIEW

**Review by ADKaster — COMMENTED** [review]
Sorry this one sat for so long! Is there a way we can add some tests for this behavior? I Know we have some for click events and such, but not sure how feasible that is atm.

**Comment by LalitSinghRana** [comment]
This change doesn't work:

https://github.com/user-attachments/assets/4c06bd01-7aaf-4216-8278-56b7ffc26939

because you're using node/cursor position before scroll event occur and not after.

**Comment by 0GreenClover0** [comment]
> Sorry this one sat for so long! Is there a way we can add some tests for this behavior? I Know we have some for click events and such, but not sure how feasible that is atm.

Ah, I didn't expect to find scroll tests but sure there are some. I've constructed one that checks for mouseenter event, but I can't find a way to make the mouseleave work with that 🤔

**Comment by 0GreenClover0** [comment]
> This change doesn't work because you're using node/cursor position before scroll event occur and **not after**.
> do-not-work.mp4
> 
> I created a simpler fix: #761.
> 
> In this PR, we are doing quite a lot of additional stuffs too, **which I think are not needed**. At least for this bug.

You're right, there seem to be some subtle differences between touch pad scroll and mouse scroll (I used the second), because of which I haven't spotted the issue. I've fixed the code more or less based on your proposed solution

I've splitted the commit into two, the second one makes the cursor change its appearance based on the hovered node

**Comment by 0GreenClover0** [comment]
This is not a fix for the full problem, there are other nuances like firing events for the scrollable element, like in the example below.
Relevant code seems to be https://github.com/LadybirdBrowser/ladybird/blob/c396054c874ca19307ccdad1d9c786ef4ab74547/Userland/Libraries/LibWeb/Page/EventHandler.cpp#L188-L193 but I can't find a proper way to fix it 🤔
```css
<style>
.scrollable {
    overflow-y: scroll;
    width: 100px;
    height: 300px;
    scrollbar-width: none;
}

.item {
    width: 100px;
    height: 100px;
    box-sizing: border-box;
    border: 1px solid black;
}
</style>
<div class="scrollable">
    <div id="test" class="item">1</div>
    <div class="item">2</div>
    <div class="item">3</div>
    <div class="item">4</div>
    <div class="item">5</div>
    <div class="item">6</div>
    <div class="item">7</div>
</div>
<script>
    console.log("Event test");

    function mouseEnter() {
        console.log("mouse enter");
    }

    function mouseLeave() {
        console.log("mouse leave");
    }

    document.querySelector('#test').addEventListener('mouseenter', mouseEnter);
    document.querySelector('#test').addEventListener('mouseleave', mouseLeave);
</script>
```

**Pull request closed without merging**
