### PR TITLE
CMake: fix Makefile build on case-insensitive file system

### PR DESCRIPTION
**Pull request by vitalyster**
Ladybird build scripts uses CMake Ninja generator. These changes will help to build Ladybird using different CMake generators (e.g. Makefile)

### CODE REVIEW

**Comment by circl-lastname** [comment]
Hello! What does this exactly Fix? Please title the commit accordingly and provide a description as to why it's needed

**Comment by ADKaster** [comment]
This patch does not fix building with Makefiles. `make` in a `-G "Unix Makefiles"` build fails on our python scripts expecting ninja-isms, not on target names.

**Comment by vitalyster** [comment]
@ADKaster I have successfully build using make under macOS, let me know where it is fails for you.
The only issue I had is absence of expected directories in TIFFGenerator.py and some other generated targets when building out of source tree, that will be addressed in next patch.

**Comment by ADKaster** [comment]
Right, I saw an error in Tiff generator.py. but why is the separate target name required on macOS?

**Comment by vitalyster** [comment]
Maybe because of case-insensitive file system?

**Comment by vitalyster** [comment]
Screenshot 2024-09-04 at 21 20 13
Without this patch Makefile generator overwrite ImageDecoder.dir with imagedecoder.dir and fails

**Pull request merged**
