### PR TITLE
LibWeb: Implement object-fit: scale-down

### PR DESCRIPTION
**Pull request by shlyakpavel**
This is not enough to pass tests https://wpt.fyi/results/css/css-images?label=master&label=experimental&product=chrome&product=ladybird&product=firefox&product=safari&aligned due to other issues

I will either find a WPT to work as regression test, or make a simple test myself

**Accidentally dublicates #2856. Better review and merge that one!**

### CODE REVIEW

**Comment by shlyakpavel** [comment]
It actually breaks https://wpt.live//css/css-images/object-fit-scale-down-png-001e.html hmm

**Comment by shlyakpavel** [comment]
It actually fixes that, while WPT.sh reports it breaks it hmmmmmmm

**Comment by InvalidUsernameException** [comment]
I opened a similar PR a couple days ago, see #2856.

Weird coincidence, I think this code was unchanged for over a year when I looked at the history.

**Comment by shlyakpavel** [comment]
@InvalidUsernameException wow didn't see that coming... I just ran "Random FIXME" roulette...

**Comment by shlyakpavel** [comment]
Superseded by https://github.com/LadybirdBrowser/ladybird/pull/2856

**Pull request closed without merging**
