### PR TITLE
LibWeb: Layout the fieldset's rendered legend

### PR DESCRIPTION
**Pull request by kostyafarber**
This fixes the legend position on my website :^) https://kostyafarber.com/about

with change:
image

without change:
image

### CODE REVIEW

**Comment by kostyafarber** [comment]
This fixes the legend position on my website :^) https://kostyafarber.com/about

with change:
image

without change:
image

**Comment by tcl3** [comment]
I've not looked at the code, but this causes regressions in the following WPT tests:
* http://wpt.live/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/fieldset-calculating-min-max-content.html
* http://wpt.live/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/legend-inline-position-with-fieldset-padding.html
* http://wpt.live/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/fieldset-baseline.html
* http://wpt.live/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/fieldset-transform-translatez.html
* http://wpt.live/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/legend-position-relative-2.html

And fixes a failing subtest in this test::
* http://wpt.live/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/legend.html

**Comment by kostyafarber** [comment]
Thanks for catching that out, I’ll have a look at those regressions then and see what’s going on. 

I’ll import the fixed test.

**Comment by kostyafarber** [comment]
> (commit message: "Layout" is a noun, "Lay out" is the verb.)

That it is, I will update.

**Comment by kostyafarber** [comment]
I've asked the discord but haven't got a response. I am wary to start implementing any feature (removing the legend from the clipped area) that isn't covered by the spec, as I've been told in the past that we should match reality and not just try pass wpt tests :^).

What is the ways forward here?

**Comment by kostyafarber** [comment]
@tcl3 can we get a review on this now please?

**Comment by AtkinsSJ** [comment]
I'm happy merging this. Regressions are sad, but when it's because they were false positives before, I don't think it makes sense for them to block improvements. IMO, it'd be worth asking someone in the whatwg what the correct behaviour for that is meant to be.

**Review by tcl3 — APPROVED** [review]
Sorry for the delay in getting to this!

I agree with Sam. Looking at the newly-failing tests, it looks like they weren't really correct anyway. What we have here is clearly an improvement on what we had before. Thanks for working on this!

**Pull request merged**
