### PR TITLE
LibWeb/CSS: Shorten the length of srgb serialization 

### PR DESCRIPTION
**Pull request by LucasChollet**
The alpha component is stored in an 8 bit values, anything after the second digit is meaningless.

This fixes 33 subtests in css/css-color.

### CODE REVIEW

**Comment by LucasChollet** [comment]
And a small clean up commit while touching the file :^)

**Comment by tcl3** [comment]
This change yields improvements in these WPT tests:
* http://wpt.live/css/css-color/parsing/color-computed.html
* http://wpt.live/css/css-color/parsing/color-valid-hsl.html
* http://wpt.live/css/css-color/parsing/color-valid-rgb.html
* http://wpt.live/css/css-color/parsing/color-valid.html
* http://wpt.live/css/css-color/parsing/color-computed-hsl

Is it possible to import these tests using `./Meta/WPT.sh import`?

**Comment by yyny** [comment]
Shouldn't that be three digits?

```c
0 / 255.0 => 0.00
1 / 255.0 => 0.00
```

**Comment by LucasChollet** [comment]
> Shouldn't that be three digits?

I did my logic wrong and was then comforted by the green tests, this is indeed plain wrong.

---

The actual solution is a bit tricky, though. AFAIU, the spec requires you to have enough precision to be able to roundtrip with 8 bits value. I tested it with script, and it works fine in ladybird:

```html
<!DOCTYPE html>
<html>
<body></body>
<script>
function testColorSerialization(inputColor) {
    const element = document.createElement('div');
    element.style.color = inputColor;
    document.body.appendChild(element);
    const serializedColor = getComputedStyle(element).color;
    document.body.removeChild(element);
    return serializedColor;
}

pass = true;

for (i = 0; i < 255; ++i) {
    input = "rgba(0, 0, 0," + i / 255 + ")"
    ser = testColorSerialization(input);
    channels = ser.match(/[0-9]*\.?[0-9]+/g);
    alpha = channels[channels.length - 1];

    if (Math.round(alpha * 255) !== i) {
        console.log(alpha + ": " + input + " -> " + ser);
        pass = false;
    }
}
console.log(pass ? "Pass" : "Fail");
</script>
```

However, the WPT tests are way more restrictive than the spec: it requires `128.f / 255` to be serialized as exactly `0.5`. You probably kinda need to bend over backwards to achieve this. Here is an example of how Firefox does its rounding.
Screenshot from 2024-11-26 17-27-09

---
Good to know that Safari was no better than us in 2018 https://github.com/web-platform-tests/wpt/commit/5aad235cfd0aa445d8a92257feea6bf49e3e14bf. But if they changed that it probably means that it is required for web compatibility, and thus we will need to do it as well.

**Comment by AtkinsSJ** [comment]
It's currently skipped, but this should also fix a bunch of issues in `/css/cssom/serialize-values.html` and maybe some other serialization tests too.

**Review by AtkinsSJ — CHANGES_REQUESTED** [review]
`Text/input/wpt-import/css/css-color/parsing/color-computed-hsl.html` is timing out on CI. It's sad, but can you add that to the skipped list?

Otherwise, I don't understand the maths here but I trust the results. :^)

**Comment by LucasChollet** [comment]
Let's give it another try now that #2714 has been merged.

**Review by AtkinsSJ — APPROVED** [review]

**Pull request merged**
